# Generated by Django 3.0.7 on 2020-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('externalTax', models.FloatField()),
            ],
        ),
    ]
