# Generated by Django 3.0.7 on 2020-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200619_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(default='comment', max_length=500),
            preserve_default=False,
        ),
    ]
