# Generated by Django 3.0.7 on 2020-06-20 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200620_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
